DATAES-741 / Tests fail due to Elasticsearch cluster 'blocks' on nearly-full file-systems.
If a filesystem available space is lower than 5-10%, even though it may be dozens of gigabytes, Elasticsearch  may block all the indices making them work in read-only mode. In such a case, tests fail with messages like the following:

org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)]

The problem is well-known: https://stackoverflow.com/questions/50609417/elasticsearch-error-cluster-block-exception-forbidden-12-index-read-only-all

The idea of the fix is to configure Elasticsearch with absolute (instead of relative, using percentage) watermarks of a sensible size (like 1Gb) that are ok for tests.